9_Distinct Echo Substrings (HASHING)
LetsGrowMoreCommunity/DSA-Playyard pull request #245
Opened 2021-07-28 23:22 UTC by soma2000-lang

#222 
Code writtten in C++

2021-07-28 23:22 UTC, soma2000-lang commented
@Debashish-hub please check

2021-07-29 01:36 UTC, Debashish-hub requested changes

2021-07-29 01:36 UTC, Debashish-hub commented on Hashing/C++/9_Distinct Echo Substrings (HASHING) .cpp
> +distinctEchoSubstrings(string text);
Write proper main function. You need to print it. @soma2000-lang

2021-07-29 06:14 UTC, soma2000-lang commented
@Debashish-hub  check now

2021-07-29 07:12 UTC, Debashish-hub commented
> @Debashish-hub check now

Where are you printing the output?

2021-07-29 07:32 UTC, soma2000-lang commented
@Debashish-hub  Sorry .done check now

2021-07-29 10:07 UTC, Debashish-hub requested changes

2021-07-29 10:07 UTC, Debashish-hub commented on Hashing/C++/9_Distinct Echo Substrings (HASHING) .cpp
> +distinctEchoSubstrings(string text);
You are returning s.size() in the function. You just need to print distinctEchoSubstrings(string text) not s.size()
@soma2000-lang

2021-07-29 21:39 UTC, soma2000-lang commented
@Debashish-hub  actually in this question I was asked to print the  no of the distict echo substrings so in this code inserted all this distinct echoes in  s.So the size of s will be now my no of disctinct echoes so I am just calling this function and returning s.size()

2021-07-29 22:12 UTC, soma2000-lang commented
@Debashish-hub  please check

2021-07-30 01:30 UTC, Debashish-hub requested changes

2021-07-30 01:30 UTC, Debashish-hub commented on Hashing/C++/9_Distinct Echo Substrings (HASHING) .cpp
> +class Solution {
You are using class but not declaring class in main function. Either declare remove the class or declare class and obj in main. @soma2000-lang

2021-08-04 05:20 UTC, soma2000-lang commented
@Debashish-hub  please check now

2021-08-06 05:13 UTC, soma2000-lang commented
@Debashish-hub why did u close this??

2021-08-06 05:18 UTC, merged